services:
  - type: web
    name: defi-ai-backend
    runtime: python
    rootDir: backend
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: GROQ_API_KEY
        sync: false
      - key: FRONTEND_URL
        value: https://frontend-teal-five-45.vercel.app
      - key: FRONTEND_URL2
        value: https://frontend-gzihc2rum-jeshwanth-as-projects.vercel.app
